# Generated by Django 4.2.23 on 2025-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do tutorial', null=True, verbose_name='Descrição')),
                ('link_conteudo', models.URLField(help_text='URL para o vídeo ou artigo do tutorial', verbose_name='Link do conteúdo')),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('texto', 'Texto')], help_text='Diferencia se o tutorial é em vídeo ou texto', max_length=10, verbose_name='Tipo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
                'db_table': 'tutoriais_tutorial',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
