# Generated by Django 4.2.23 on 2025-06-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.TextField(verbose_name='Texto da alternativa')),
                ('correta', models.BooleanField(default=False, help_text='TRUE se esta for a resposta correta, FALSE caso contrário', verbose_name='Correta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'db_table': 'quiz_alternativa',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(help_text='O texto da pergunta do quiz', verbose_name='Enunciado')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=10, verbose_name='Dificuldade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'db_table': 'quiz_pergunta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField(verbose_name='Acertou')),
                ('data_tentativa', models.DateTimeField(auto_now_add=True, verbose_name='Data da tentativa')),
                ('alternativa_selecionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.alternativa', verbose_name='Alternativa selecionada')),
            ],
            options={
                'verbose_name': 'Resultado do Quiz',
                'verbose_name_plural': 'Resultados do Quiz',
                'db_table': 'quiz_resultadoquiz',
                'ordering': ['-data_tentativa'],
            },
        ),
    ]
