# Generated by Django 4.2.23 on 2025-06-20 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoquiz',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='resultadoquiz',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='quiz.pergunta', verbose_name='Pergunta'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(condition=models.Q(('correta', True)), fields=('pergunta',), name='unique_correct_answer_per_question'),
        ),
    ]
